name: langchain-pdf
channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.11
  - python-dotenv=1.0.0
  - boto3=1.26.122
  - botocore=1.29.122
  - celery=5.3.1
  - click=8.1.3
  - Werkzeug=2.3.1
  - invoke=2.2.0
  - pypdf=3.15.4
  - watchdog=3.0.0
  - tiktoken=0.4.0
  - backoff=2.2.1
  - pip=24.0
  - pip:
      - langchain==0.1.16
      - openai==1.16.1
      - langchain-openai==0.1.3
      - uuid==1.30
      - pinecone-client==3.2.2
      - langfuse==1.0.18
      - flask_cors==4.0.0
      - redis==5.0.0
      - Flask==2.3.1
      - flask_sqlalchemy==3.0.3
      - flask_cors==4.0.0